---
title: "2025_Floristics-Pollinators"
author: "Michelle DePrenger-Levin"
date: "2025-12-15"
output: html_document
---

```{r}

library(tidyverse) #for making figures
library(dplyr) #data manipulation
library(tidyr) #more data manipulation
library(viridis) #colorblind friendly color palette
library(ggthemes) #to make ggplots pretty
# library(hrbrthemes) #to make ggplots pretty
# library(waffle)

```

```{r}
setwd("C:/Users/deprengm/Denver Botanic Gardens/Conservation - Restoration/CommonGround Golf Course/Data")
```


```{r}

#species richness data
data2023 <- read.csv("2023_VegPlot_Data/2023_PlantSurveys_SpeciesData.csv") #read in csv
data2024 <- read.csv("2024_VegPlot_Data/2024_PlantSurveys_SpeciesRichness.csv")
data2025 <- read.csv("2025_VegPlot_Data/entirePlotTaxa_1.csv") ## not in nice format, missing data
CommonGround0 <- read.csv("2025_VegPlot_Data/CommonGround_SeedlingExperiment_0.csv")
seeded <- read.csv("SeededSpList.csv") # made list by hand

data2025 <- data2025 %>%
  mutate(Date = format(as.Date(CreationDate, format="%m/%d/%Y %H:%M"), "%m/%d/%Y")) %>%
  mutate(Plot_number = Plot) %>%
  left_join(CommonGround0, by = c("ParentGlobalID" = "GlobalID", "Plot" = "Plot")) %>%
  mutate(Random_quadrat = NA,
         Origin = NA,
         C.value = NA,
         Wetland_indicator_status = NA) %>% 
  ## Change the species to codes 
  rowwise() %>%
  mutate(Species = case_when(grepl("_", Taxon) ~ paste0(substring(strsplit(Taxon, "_")[[1]][1], 1,3),
                                                        substring(strsplit(Taxon, "_")[[1]][2], 1,3)),
                             TRUE ~ Taxon)) %>%
  mutate(Seeded. = case_when(Species %in% seeded$Species ~ "Yes",
                             TRUE ~ "No")) %>%
  ungroup() %>%
  select(Date.x, Plot_number, Treatment, Random_quadrat, Species, 
         Seeded., Origin, C.value, Wetland_indicator_status) %>%
  rename(Date = Date.x) %>%
  mutate(Treatment = case_when(Treatment == "control" ~ "C",
                               Treatment == "seeded" ~ "S",
                               Treatment == "aerated_seeded" ~ "A/S",
                               Treatment == "aerated_seeded_harrowed" ~ "A/S/H"))

# data2025 %>%
#   rowwise() %>%
#   # Change the species to codes
#   mutate(SpeciesCode = case_when(grepl("_", Species) ~ paste0(substring(strsplit(Species, "_")[[1]][1], 1,3),
#                                                         substring(strsplit(Species, "_")[[1]][2], 1,3)),
#                              TRUE ~ Species))


planttaxa <- data2024 %>%
  dplyr::select(Date:Wetland_indicator_status) %>%
  bind_rows(data2023) %>%
  bind_rows(data2025) %>%
  mutate(Species = tolower(Species)) %>%
  filter(Plot_number != "") %>%
  mutate(Year = format(as.Date(Date, format="%m/%d/%Y"),"%Y"))

table(data2024$Species, data2024$Seeded.)
table(data2023$Species, data2023$Seeded.)
table(data2025$Species, data2025$Seeded.)


```

Figures
```{r}

# summaries of species by plot
planttaxa %>%
  group_by(Plot_number, Treatment) %>%
  summarise_all(n_distinct)
  
table(planttaxa$Date, useNA = "ifany")

planttaxa %>%
  filter(!grepl("\\?", Species)) %>%
  filter(!grepl("unk", Species)) %>%
  filter(!grepl("unmowed", Species)) %>%
  filter(Species != "") %>%
  mutate(Treatment = factor(Treatment, levels = c("C","S", "A/S", "A/S/H"))) %>%
  filter(!is.na(Seeded.) & Seeded. != "") %>%
  group_by(Year, Plot_number, Treatment, Species, Seeded.) %>%
  dplyr::summarise(n = n()) %>%
  mutate(SpIn = ifelse(n > 0, 1, 0)) %>%
  group_by(Year, Plot_number, Treatment, Seeded.) %>%
  dplyr::summarise(SpNum = sum(SpIn)) %>%
ggplot(   aes(Treatment, SpNum, fill = Seeded.))+
  geom_boxplot(position = position_dodge(width = 0.75), width = 0.5) +
  geom_point(position = position_jitterdodge(jitter.height = 0, jitter.width = 0.1, dodge.width = 0.75))+
  theme_bw()+
  scale_fill_manual(values = c("slateblue","seagreen")) +
  facet_wrap(~Year) +
  ylab("Number of species observations")

planttaxa %>%
  filter(!grepl("\\?", Species)) %>%
  filter(!grepl("unk", Species)) %>%
  filter(!grepl("unmowed", Species)) %>%
  filter(Species != "") %>%
  mutate(Treatment = factor(Treatment, levels = c("C","S", "A/S", "A/S/H"))) %>%
  filter(!is.na(Seeded.) & Seeded. != "") %>%
  group_by(Year, Plot_number, Treatment, Species, Seeded.) %>%
  dplyr::summarise(n = n()) %>%
  mutate(SpIn = ifelse(n > 0, 1, 0)) %>%
  group_by(Year, Plot_number, Treatment, Seeded.) %>%
  dplyr::summarise(SpNum = sum(SpIn)) %>%
ggplot(   aes(Treatment, SpNum, fill = Year))+
  geom_boxplot(position = position_dodge(width = 0.75), width = 0.5) +
  geom_point(position = position_jitterdodge(jitter.height = 0, jitter.width = 0.1, dodge.width = 0.75))+
  theme_bw()+
  scale_fill_manual(values = c("grey10","grey50","grey70")) +
  facet_wrap(~Seeded., scales = "free") +
  ylab("Number of species observations")


planttaxa %>%
  group_by(Species) %>%
  dplyr::summarise(n = n()) %>%
  print(n = 100)
```



# Pollinators  
```{r}

pollinator_df2024 <- read.csv("PollinatorObservations_data/2024_PollinatorObs_Data.csv")
pollinator_df2025 <- read.csv("PollinatorObservations_data/2025_PollinatorObs_Data.csv")


pollinator_df <- pollinator_df2024 %>%
  bind_rows(pollinator_df2025) %>%
  mutate(Date = as.Date(Date, format= "%m/%d/%Y")) %>%
  mutate(Treatment = case_when(Treatment == "ASH" ~ "A/S/H",
                               Treatment == "S " ~ "S",
                               Treatment == "AS " ~ "A/S",
                               Treatment == "AS" ~ "A/S",
                               TRUE ~ Treatment)) %>%
  filter(Treatment != "") %>%
  mutate(Treatment = factor(Treatment, levels = c("C","S", "A/S", "A/S/H"))) %>%
  mutate(Year = format(as.Date(Date, format="%m/%d/%Y"),"%Y"))

pollinator_df %>%
  filter(!(Year %in% c(2024, 2025)))


ggplot(pollinator_df, aes(x=Treatment,y=Total, fill = Treatment))+
  geom_boxplot()+
  theme_bw()+
  ggtitle("2024-2025 Pollinators")+
  facet_wrap(~ Year)

```


```{r}

pollinator_df_long <- pollinator_df %>%
  select(Year, Plot, Treatment:Other.bee, Ants:Other) %>%
  pivot_longer(cols = c(Honey.bees, Bumble.bees, Other.bee, Ants, 
                        Butterfly, Beetle, Wasp, Flies, Other), 
               names_to = "Guild", 
               values_to = "Obs")

pollinator_df_long %>%
  group_by(Year, Plot, Treatment, Guild) %>%
  summarise(TotalObs = sum(Obs)) %>%
ggplot(    aes(Guild, TotalObs, fill = Treatment)) +
  geom_boxplot() +
  geom_point(position = position_jitterdodge(jitter.height = 0, jitter.width = 0.1)) +
  facet_wrap(~ Year) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ylab("Total observations")

```

